name: PR Develop => Master
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version of the release"
        required: true
        default: "1.0.0"
      developmentVersion:
        description: "Version of the release"
        required: true
        default: "1.0.0-SNAPSHOT"
jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: New branch
        run: |
          git checkout -B ${{ github.event.inputs.releaseVersion }}
          git push origin ${{ github.event.inputs.releaseVersion }}
      - name: Create Pull Request
        id: cpr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.event.inputs.releaseVersion }}"
          destination_branch: master
          pr_title: "[RELEASE] ${{ github.event.inputs.releaseVersion }}"
          pr_label: release
          pr_assignee: 0ddlyoko
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pr_url }}"
